Repository brain-tec/server-auth, pull requests merged in 2022-01, with the labels that each got.

#215 Syncing from upstream OCA/server-auth (13.0)
  README.md
  auth_saml/__manifest__.py
Labels: 13.0

#216 Syncing from upstream OCA/server-auth (14.0)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .travis.yml
  README.md
  auth_saml/__manifest__.py
Labels: 14.0

#218 [14.0][FIX] password_security: properly consider 2FA in the workflow
  README.md
  auth_signup_verify_email/README.rst
  auth_signup_verify_email/__init__.py
  auth_signup_verify_email/__manifest__.py
  auth_signup_verify_email/controllers/__init__.py
  auth_signup_verify_email/controllers/main.py
  auth_signup_verify_email/i18n/ar.po
  auth_signup_verify_email/i18n/auth_signup_verify_email.pot
  auth_signup_verify_email/i18n/de.po
  auth_signup_verify_email/i18n/es.po
  auth_signup_verify_email/i18n/fr.po
  auth_signup_verify_email/i18n/hr.po
  auth_signup_verify_email/i18n/hr_HR.po
  auth_signup_verify_email/i18n/it.po
  auth_signup_verify_email/i18n/pt_BR.po
  auth_signup_verify_email/i18n/ro.po
  auth_signup_verify_email/i18n/sl.po
  auth_signup_verify_email/i18n/tr.po
  auth_signup_verify_email/readme/CONFIGURE.rst
  auth_signup_verify_email/readme/CONTRIBUTORS.rst
  auth_signup_verify_email/readme/DESCRIPTION.rst
  auth_signup_verify_email/readme/INSTALL.rst
  auth_signup_verify_email/readme/USAGE.rst
  auth_signup_verify_email/static/description/icon.png
  auth_signup_verify_email/static/description/icon.svg
  auth_signup_verify_email/static/description/index.html
  auth_signup_verify_email/tests/__init__.py
  auth_signup_verify_email/tests/test_verify_email.py
  auth_signup_verify_email/views/signup.xml
  password_security/__manifest__.py
  password_security/controllers/__init__.py
  password_security/controllers/home.py
  password_security/controllers/main.py
  requirements.txt
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/auth_signup_verify_email/odoo/addons/auth_signup_verify_email
  setup/auth_signup_verify_email/setup.py
Labels: 14.0.project_to_553
