Repository brain-tec/server-auth, pull requests merged in 2024-10, with the labels that each got.

#499 Syncing from upstream OCA/server-auth (17.0)
  auth_signup_verify_email/i18n/fi.po
Labels: 17.0

#502 Syncing from upstream OCA/server-auth (17.0)
  auth_api_key/i18n/it.po
Labels: 17.0

#503 Syncing from upstream OCA/server-auth (17.0)
  README.md
  auth_api_key/README.rst
  auth_api_key/__manifest__.py
  auth_api_key/readme/DESCRIPTION.md
  auth_api_key/static/description/index.html
Labels: 17.0

#504 Syncing from upstream OCA/server-auth (18.0)
  README.md
  auth_api_key/README.rst
  auth_api_key/__init__.py
  auth_api_key/__manifest__.py
  auth_api_key/i18n/auth_api_key.pot
  auth_api_key/i18n/it.po
  auth_api_key/models/__init__.py
  auth_api_key/models/auth_api_key.py
  auth_api_key/models/ir_http.py
  auth_api_key/models/res_company.py
  auth_api_key/models/res_config_settings.py
  auth_api_key/pyproject.toml
  auth_api_key/readme/CONFIGURE.md
  auth_api_key/readme/CONTRIBUTORS.md
  auth_api_key/readme/CREDITS.md
  auth_api_key/readme/DESCRIPTION.md
  auth_api_key/readme/USAGE.md
  auth_api_key/security/ir.model.access.csv
  auth_api_key/static/description/icon.png
  auth_api_key/static/description/index.html
  auth_api_key/tests/__init__.py
  auth_api_key/tests/test_auth_api_key.py
  auth_api_key/views/auth_api_key.xml
  auth_api_key/views/res_config_settings.xml
  base_user_empty_password/README.rst
  base_user_empty_password/__init__.py
  base_user_empty_password/__manifest__.py
  base_user_empty_password/i18n/base_user_empty_password.pot
  base_user_empty_password/models/__init__.py
  base_user_empty_password/models/res_users.py
  base_user_empty_password/pyproject.toml
  base_user_empty_password/readme/CONTRIBUTORS.md
  base_user_empty_password/readme/CREDITS.md
  base_user_empty_password/readme/DESCRIPTION.md
  base_user_empty_password/security/ir.model.access.csv
  base_user_empty_password/static/description/icon.png
  base_user_empty_password/static/description/index.html
  base_user_empty_password/tests/__init__.py
  base_user_empty_password/tests/test_user_empty_password.py
  base_user_empty_password/views/res_users.xml
  base_user_empty_password/wizard/__init__.py
  base_user_empty_password/wizard/empty_password.py
  base_user_empty_password/wizard/empty_password.xml
  setup/_metapackage/pyproject.toml
Labels: 18.0

#505 Syncing from upstream OCA/server-auth (18.0)
  auth_api_key/i18n/it.po
  base_user_empty_password/i18n/it.po
Labels: 18.0

#506 Syncing from upstream OCA/server-auth (17.0)
  README.md
  impersonate_login/README.rst
  impersonate_login/__manifest__.py
  impersonate_login/models/impersonate_log.py
  impersonate_login/static/description/index.html
Labels: 17.0

#507 Syncing from upstream OCA/server-auth (18.0)
  README.md
  auth_api_key_group/README.rst
  auth_api_key_group/__init__.py
  auth_api_key_group/__manifest__.py
  auth_api_key_group/i18n/auth_api_key_group.pot
  auth_api_key_group/i18n/it.po
  auth_api_key_group/models/__init__.py
  auth_api_key_group/models/auth_api_key.py
  auth_api_key_group/models/auth_api_key_group.py
  auth_api_key_group/pyproject.toml
  auth_api_key_group/readme/CONTRIBUTORS.md
  auth_api_key_group/readme/CREDITS.md
  auth_api_key_group/readme/DESCRIPTION.md
  auth_api_key_group/security/ir.model.access.csv
  auth_api_key_group/static/description/icon.png
  auth_api_key_group/static/description/index.html
  auth_api_key_group/tests/__init__.py
  auth_api_key_group/tests/test_auth_api_key_group.py
  auth_api_key_group/views/auth_api_key_group_view.xml
  auth_api_key_group/views/auth_api_key_view.xml
  auth_api_key_server_env/README.rst
  auth_api_key_server_env/__init__.py
  auth_api_key_server_env/__manifest__.py
  auth_api_key_server_env/i18n/auth_api_key_server_env.pot
  auth_api_key_server_env/i18n/it.po
  auth_api_key_server_env/models/__init__.py
  auth_api_key_server_env/models/auth_api_key.py
  auth_api_key_server_env/pyproject.toml
  auth_api_key_server_env/readme/CONTRIBUTORS.md
  auth_api_key_server_env/readme/CREDITS.md
  auth_api_key_server_env/readme/DESCRIPTION.md
  auth_api_key_server_env/static/description/icon.png
  auth_api_key_server_env/static/description/index.html
  auth_api_key_server_env/tests/__init__.py
  auth_api_key_server_env/tests/test_auth_api_key.py
  setup/_metapackage/pyproject.toml
Labels: 18.0

#508 Syncing from upstream OCA/server-auth (18.0)
  .copier-answers.yml
  .eslintrc.yml
  .pre-commit-config.yaml
  .prettierrc.yml
  auth_api_key/views/auth_api_key.xml
  auth_api_key/views/res_config_settings.xml
  eslint.config.cjs
  prettier.config.cjs
Labels: 18.0

#509 Syncing from upstream OCA/server-auth (16.0)
  README.md
  auth_oidc/README.rst
  auth_oidc/__manifest__.py
  auth_oidc/readme/CONFIGURE.md
  auth_oidc/static/description/index.html
Labels: 16.0

#510 Syncing from upstream OCA/server-auth (17.0)
  README.md
  auth_oidc/README.rst
  auth_oidc/__manifest__.py
  auth_oidc/controllers/main.py
  auth_oidc/data/auth_oauth_data.xml
  auth_oidc/demo/local_keycloak.xml
  auth_oidc/i18n/auth_oidc.pot
  auth_oidc/i18n/es.po
  auth_oidc/i18n/it.po
  auth_oidc/i18n/zh_CN.po
  auth_oidc/models/auth_oauth_provider.py
  auth_oidc/readme/CONFIGURE.md
  auth_oidc/static/description/index.html
  auth_oidc/static/description/oauth-microsoft_azure-select_account.png
  auth_oidc/tests/test_auth_oidc_auth_code.py
  auth_oidc/views/auth_oauth_provider.xml
Labels: 17.0

#511 [t151701] global default SAML provider
  auth_saml/i18n/de.po
  auth_saml/models/__init__.py
  auth_saml/models/res_company.py
  auth_saml/models/res_config_settings.py
  auth_saml/models/res_users.py
Labels: enhancement, 15.0.project_sv_559

#512 Syncing from upstream OCA/server-auth (17.0)
  auth_oidc/i18n/it.po
Labels: 17.0

#513 Syncing from upstream OCA/server-auth (18.0)
  README.md
  auth_oidc/README.rst
  auth_oidc/__init__.py
  auth_oidc/__manifest__.py
  auth_oidc/controllers/__init__.py
  auth_oidc/controllers/main.py
  auth_oidc/data/auth_oauth_data.xml
  auth_oidc/demo/local_keycloak.xml
  auth_oidc/i18n/auth_oidc.pot
  auth_oidc/i18n/es.po
  auth_oidc/i18n/it.po
  auth_oidc/i18n/zh_CN.po
  auth_oidc/models/__init__.py
  auth_oidc/models/auth_oauth_provider.py
  auth_oidc/models/res_users.py
  auth_oidc/pyproject.toml
  auth_oidc/readme/CONFIGURE.md
  auth_oidc/readme/CONTRIBUTORS.md
  auth_oidc/readme/DESCRIPTION.md
  auth_oidc/readme/HISTORY.md
  auth_oidc/readme/INSTALL.md
  auth_oidc/readme/ROADMAP.md
  auth_oidc/readme/USAGE.md
  auth_oidc/static/description/icon.png
  auth_oidc/static/description/index.html
  auth_oidc/static/description/oauth-microsoft_azure-api_permissions.png
  auth_oidc/static/description/oauth-microsoft_azure-optional_claims.png
  auth_oidc/static/description/odoo-azure_ad_multitenant.png
  auth_oidc/tests/__init__.py
  auth_oidc/tests/keycloak/keycloak-config.json
  auth_oidc/tests/keycloak/keycloak.sh
  auth_oidc/tests/test_auth_oidc_auth_code.py
  auth_oidc/views/auth_oauth_provider.xml
  requirements.txt
  setup/_metapackage/pyproject.toml
  test-requirements.txt
Labels: 18.0

#514 Syncing from upstream OCA/server-auth (16.0)
  auth_oauth_ropc/i18n/it.po
Labels: 16.0
