Repository brain-tec/server-auth, pull requests merged in 2024-12, with the labels that each got.

#521 Syncing from upstream OCA/server-auth (14.0)
  README.md
  auth_api_key_group/i18n/it.po
  auth_api_key_server_env/i18n/it.po
  auth_jwt_demo/i18n/it.po
  auth_oauth_autologin/i18n/it.po
  auth_oidc_environment/i18n/it.po
  auth_saml/README.rst
  auth_saml/__manifest__.py
  auth_saml/i18n/it.po
  auth_saml/models/auth_saml_provider.py
  base_user_empty_password/i18n/it.po
  base_user_show_email/i18n/it.po
  user_log_view/i18n/it.po
  users_ldap_mail/i18n/it.po
  vault/i18n/it.po
  vault_share/i18n/it.po
Labels: 14.0

#522 Syncing from upstream OCA/server-auth (14.0)
  auth_oauth_multi_token/i18n/it.po
  auth_oidc/i18n/it.po
Labels: 14.0

#523 [18.0][MIG] auth_admin_passkey: Migration to 18.0
  auth_admin_passkey/README.rst
  auth_admin_passkey/__init__.py
  auth_admin_passkey/__manifest__.py
  auth_admin_passkey/i18n/ar.po
  auth_admin_passkey/i18n/auth_admin_passkey.pot
  auth_admin_passkey/i18n/ca.po
  auth_admin_passkey/i18n/da.po
  auth_admin_passkey/i18n/de.po
  auth_admin_passkey/i18n/el_GR.po
  auth_admin_passkey/i18n/es.po
  auth_admin_passkey/i18n/es_ES.po
  auth_admin_passkey/i18n/fi.po
  auth_admin_passkey/i18n/fr.po
  auth_admin_passkey/i18n/fr_CH.po
  auth_admin_passkey/i18n/fr_FR.po
  auth_admin_passkey/i18n/hr.po
  auth_admin_passkey/i18n/hr_HR.po
  auth_admin_passkey/i18n/it.po
  auth_admin_passkey/i18n/nl.po
  auth_admin_passkey/i18n/nl_NL.po
  auth_admin_passkey/i18n/pt.po
  auth_admin_passkey/i18n/pt_BR.po
  auth_admin_passkey/i18n/ro.po
  auth_admin_passkey/i18n/sl.po
  auth_admin_passkey/i18n/tr.po
  auth_admin_passkey/i18n/tr_TR.po
  auth_admin_passkey/i18n/zh_CN.po
  auth_admin_passkey/models/__init__.py
  auth_admin_passkey/models/res_users.py
  auth_admin_passkey/pyproject.toml
  auth_admin_passkey/readme/CONFIGURE.md
  auth_admin_passkey/readme/CONTRIBUTORS.md
  auth_admin_passkey/readme/DESCRIPTION.md
  auth_admin_passkey/static/description/icon.png
  auth_admin_passkey/static/description/index.html
  auth_admin_passkey/tests/__init__.py
  auth_admin_passkey/tests/test_auth_admin_passkey.py
  auth_admin_passkey/tests/test_ui.py
Labels: 18.0.t154502

#524 [t154502][18.0][MIG] auth_admin_passkey: Migration to 18.0
  auth_admin_passkey/README.rst
  auth_admin_passkey/__init__.py
  auth_admin_passkey/__manifest__.py
  auth_admin_passkey/i18n/ar.po
  auth_admin_passkey/i18n/auth_admin_passkey.pot
  auth_admin_passkey/i18n/ca.po
  auth_admin_passkey/i18n/da.po
  auth_admin_passkey/i18n/de.po
  auth_admin_passkey/i18n/el_GR.po
  auth_admin_passkey/i18n/es.po
  auth_admin_passkey/i18n/es_ES.po
  auth_admin_passkey/i18n/fi.po
  auth_admin_passkey/i18n/fr.po
  auth_admin_passkey/i18n/fr_CH.po
  auth_admin_passkey/i18n/fr_FR.po
  auth_admin_passkey/i18n/hr.po
  auth_admin_passkey/i18n/hr_HR.po
  auth_admin_passkey/i18n/it.po
  auth_admin_passkey/i18n/nl.po
  auth_admin_passkey/i18n/nl_NL.po
  auth_admin_passkey/i18n/pt.po
  auth_admin_passkey/i18n/pt_BR.po
  auth_admin_passkey/i18n/ro.po
  auth_admin_passkey/i18n/sl.po
  auth_admin_passkey/i18n/tr.po
  auth_admin_passkey/i18n/tr_TR.po
  auth_admin_passkey/i18n/zh_CN.po
  auth_admin_passkey/models/__init__.py
  auth_admin_passkey/models/res_users.py
  auth_admin_passkey/pyproject.toml
  auth_admin_passkey/readme/CONFIGURE.md
  auth_admin_passkey/readme/CONTRIBUTORS.md
  auth_admin_passkey/readme/DESCRIPTION.md
  auth_admin_passkey/static/description/icon.png
  auth_admin_passkey/static/description/index.html
  auth_admin_passkey/tests/__init__.py
  auth_admin_passkey/tests/test_auth_admin_passkey.py
  auth_admin_passkey/tests/test_ui.py
Labels: 18.0.project_sv_559

#525 Syncing from upstream OCA/server-auth (17.0)
  README.md
  auth_ldaps/README.rst
  auth_ldaps/__init__.py
  auth_ldaps/__manifest__.py
  auth_ldaps/i18n/auth_ldaps.pot
  auth_ldaps/i18n/it.po
  auth_ldaps/models/__init__.py
  auth_ldaps/models/res_company_ldap.py
  auth_ldaps/pyproject.toml
  auth_ldaps/readme/CONFIGURE.md
  auth_ldaps/readme/CONTRIBUTORS.md
  auth_ldaps/readme/CREDITS.md
  auth_ldaps/readme/DESCRIPTION.md
  auth_ldaps/readme/INSTALL.md
  auth_ldaps/readme/USAGE.md
  auth_ldaps/static/description/icon.png
  auth_ldaps/static/description/index.html
  auth_ldaps/views/res_company_ldap_views.xml
  requirements.txt
  setup/_metapackage/pyproject.toml
Labels: 17.0
