Repository brain-tec/server-auth, pull requests merged in 2025-01, with the labels that each got.

#526 Syncing from upstream OCA/server-auth (18.0)
  README.md
  auth_admin_passkey/README.rst
  auth_admin_passkey/__init__.py
  auth_admin_passkey/__manifest__.py
  auth_admin_passkey/i18n/ar.po
  auth_admin_passkey/i18n/auth_admin_passkey.pot
  auth_admin_passkey/i18n/ca.po
  auth_admin_passkey/i18n/da.po
  auth_admin_passkey/i18n/de.po
  auth_admin_passkey/i18n/el_GR.po
  auth_admin_passkey/i18n/es.po
  auth_admin_passkey/i18n/es_ES.po
  auth_admin_passkey/i18n/fi.po
  auth_admin_passkey/i18n/fr.po
  auth_admin_passkey/i18n/fr_CH.po
  auth_admin_passkey/i18n/fr_FR.po
  auth_admin_passkey/i18n/hr.po
  auth_admin_passkey/i18n/hr_HR.po
  auth_admin_passkey/i18n/it.po
  auth_admin_passkey/i18n/nl.po
  auth_admin_passkey/i18n/nl_NL.po
  auth_admin_passkey/i18n/pt.po
  auth_admin_passkey/i18n/pt_BR.po
  auth_admin_passkey/i18n/ro.po
  auth_admin_passkey/i18n/sl.po
  auth_admin_passkey/i18n/tr.po
  auth_admin_passkey/i18n/tr_TR.po
  auth_admin_passkey/i18n/zh_CN.po
  auth_admin_passkey/models/__init__.py
  auth_admin_passkey/models/res_users.py
  auth_admin_passkey/pyproject.toml
  auth_admin_passkey/readme/CONFIGURE.md
  auth_admin_passkey/readme/CONTRIBUTORS.md
  auth_admin_passkey/readme/DESCRIPTION.md
  auth_admin_passkey/static/description/icon.png
  auth_admin_passkey/static/description/index.html
  auth_admin_passkey/tests/__init__.py
  auth_admin_passkey/tests/test_auth_admin_passkey.py
  auth_admin_passkey/tests/test_ui.py
  setup/_metapackage/pyproject.toml
Labels: 18.0

#530 Syncing from upstream OCA/server-auth (18.0)
  README.md
  auth_saml/README.rst
  auth_saml/__init__.py
  auth_saml/__manifest__.py
  auth_saml/controllers/__init__.py
  auth_saml/controllers/main.py
  auth_saml/data/ir_config_parameter.xml
  auth_saml/i18n/auth_saml.pot
  auth_saml/i18n/es.po
  auth_saml/i18n/fr.po
  auth_saml/i18n/it.po
  auth_saml/models/__init__.py
  auth_saml/models/auth_saml_attribute_mapping.py
  auth_saml/models/auth_saml_provider.py
  auth_saml/models/auth_saml_request.py
  auth_saml/models/ir_config_parameter.py
  auth_saml/models/res_config_settings.py
  auth_saml/models/res_users.py
  auth_saml/models/res_users_saml.py
  auth_saml/pyproject.toml
  auth_saml/readme/CONFIGURE.md
  auth_saml/readme/CONTRIBUTORS.md
  auth_saml/readme/DESCRIPTION.md
  auth_saml/readme/HISTORY.md
  auth_saml/readme/INSTALL.md
  auth_saml/readme/ROADMAP.md
  auth_saml/readme/USAGE.md
  auth_saml/security/ir.model.access.csv
  auth_saml/static/description/icon.png
  auth_saml/static/description/index.html
  auth_saml/tests/__init__.py
  auth_saml/tests/data/idp.pem
  auth_saml/tests/data/sp.key
  auth_saml/tests/data/sp.pem
  auth_saml/tests/fake_idp.py
  auth_saml/tests/test_models_saml_attribute_mapping.py
  auth_saml/tests/test_pysaml.py
  auth_saml/views/auth_saml.xml
  auth_saml/views/res_config_settings.xml
  auth_saml/views/res_users.xml
  requirements.txt
  setup/_metapackage/pyproject.toml
Labels: 18.0

#531 Syncing from upstream OCA/server-auth (14.0)
  auth_api_key/i18n/it.po
Labels: 14.0

#532 Syncing from upstream OCA/server-auth (17.0)
  README.md
  auth_jwt/README.rst
  auth_jwt/__init__.py
  auth_jwt/__manifest__.py
  auth_jwt/exceptions.py
  auth_jwt/i18n/auth_jwt.pot
  auth_jwt/i18n/es.po
  auth_jwt/i18n/it.po
  auth_jwt/models/__init__.py
  auth_jwt/models/auth_jwt_validator.py
  auth_jwt/models/ir_http.py
  auth_jwt/pyproject.toml
  auth_jwt/readme/CONTRIBUTORS.md
  auth_jwt/readme/DESCRIPTION.md
  auth_jwt/readme/INSTALL.md
  auth_jwt/readme/USAGE.md
  auth_jwt/security/ir.model.access.csv
  auth_jwt/static/description/icon.png
  auth_jwt/static/description/index.html
  auth_jwt/tests/__init__.py
  auth_jwt/tests/test_auth_jwt.py
  auth_jwt/views/auth_jwt_validator_views.xml
  requirements.txt
  setup/_metapackage/pyproject.toml
Labels: 17.0

#533 [18.0][MIG] auth_saml: Migration to 18.0
  auth_saml/controllers/main.py
  auth_saml/models/res_users.py
  auth_saml/tests/fake_idp.py
  auth_saml/tests/test_pysaml.py
Labels: 18.0.t154508

#534 Syncing from upstream OCA/server-auth (18.0)
  README.md
  auth_oidc_environment/README.rst
  auth_oidc_environment/__init__.py
  auth_oidc_environment/__manifest__.py
  auth_oidc_environment/i18n/auth_oidc_environment.pot
  auth_oidc_environment/i18n/it.po
  auth_oidc_environment/models/__init__.py
  auth_oidc_environment/models/auth_oauth_provider.py
  auth_oidc_environment/pyproject.toml
  auth_oidc_environment/readme/CONFIGURE.md
  auth_oidc_environment/readme/CONTRIBUTORS.md
  auth_oidc_environment/readme/DESCRIPTION.md
  auth_oidc_environment/readme/USAGE.md
  auth_oidc_environment/static/description/icon.png
  auth_oidc_environment/static/description/index.html
  auth_oidc_environment/tests/__init__.py
  auth_oidc_environment/tests/test_auth_oidc_environment.py
  setup/_metapackage/pyproject.toml
Labels: 18.0

#535 Syncing from upstream OCA/server-auth (16.0)
  README.md
  auth_oauth_autologin/README.rst
  auth_oauth_autologin/__init__.py
  auth_oauth_autologin/__manifest__.py
  auth_oauth_autologin/controllers/__init__.py
  auth_oauth_autologin/controllers/main.py
  auth_oauth_autologin/i18n/auth_oauth_autologin.pot
  auth_oauth_autologin/models/__init__.py
  auth_oauth_autologin/models/auth_oauth_provider.py
  auth_oauth_autologin/readme/CONFIGURE.rst
  auth_oauth_autologin/readme/DESCRIPTION.rst
  auth_oauth_autologin/readme/USAGE.rst
  auth_oauth_autologin/static/description/icon.png
  auth_oauth_autologin/static/description/index.html
  auth_oauth_autologin/static/src/js/web_login.js
  auth_oauth_autologin/views/assets.xml
  auth_oauth_autologin/views/auth_oauth_provider.xml
  setup/_metapackage/VERSION.txt
  setup/_metapackage/setup.py
  setup/auth_oauth_autologin/odoo/addons/auth_oauth_autologin
  setup/auth_oauth_autologin/setup.py
Labels: 16.0

#536 Syncing from upstream OCA/server-auth (16.0)
  auth_oauth_autologin/i18n/fr.po
  auth_oidc/i18n/fr.po
Labels: 16.0

#537 Syncing from upstream OCA/server-auth (16.0)
  auth_oauth_autologin/i18n/it.po
Labels: 16.0

#538 Syncing from upstream OCA/server-auth (18.0)
  auth_saml/i18n/fr.po
Labels: 18.0

#539 Syncing from upstream OCA/server-auth (16.0)
  auth_oauth_ropc/i18n/it.po
Labels: 16.0
