Repository brain-tec/server-auth, pull requests merged in 2025-07, with the labels that each got.

#599 Syncing from upstream OCA/server-auth (16.0)
  README.md
  users_ldap_populate/README.rst
  users_ldap_populate/__manifest__.py
  users_ldap_populate/models/users_ldap.py
  users_ldap_populate/static/description/index.html
Labels: 16.0

#601 Syncing from upstream OCA/server-auth (17.0)
  README.md
  users_ldap_populate/README.rst
  users_ldap_populate/__manifest__.py
  users_ldap_populate/models/users_ldap.py
  users_ldap_populate/static/description/index.html
Labels: 17.0

#603 [t163020] Fix login screen when no saml_providers
  auth_saml/views/auth_saml.xml
Labels: 18.0.project_sv_559
